name: Build Docker Image

on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build image
        run: docker build -f .docker/Dockerfile.docker -t storyscript/studio .

      - name: Login to Docker HUB
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWD
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWD: ${{ secrets.DOCKER_PASSWD }}
      
      - name: Push the image
        run: docker push storyscript/studio