name: Playground Storyscript verification

on: [pull_request]

jobs:
  storyscript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7.x'
          architecture: x64

      - name: Install storyscript
        run: pip install storyscript

      - name: Test storyscript compilation of sample stories
        run: storyscript compile src/samples/{counter,file,gfs}.story
